name: tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - check:types
          - test
    name: ${{ matrix.job }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v3
        id: nodeCache
        with:
          key: node-modules-node-20-${{ hashFiles('yarn.lock') }}
          path: node_modules/**
      # - uses: actions/cache@v3
      #   id: cypressCache
      #   with:
      #     key: node-modules-node-20-${{ hashFiles('yarn.lock') }}
      #     path: node_modules/**
      - run: yarn install
        if: steps.nodeCache.outputs.cache-hit != 'true'
      - run: yarn ${{ matrix.job }}
